Update fs-extra dependency
In a futile attempt to resolve these explosions during `npm run test`
runs:

```
    ReferenceError: internalBinding is not defined

      at fs.js:25:1
      at req_ (node_modules/natives/index.js:137:5)
      at Object.req [as require] (node_modules/natives/index.js:54:10)
      at Object.<anonymous> (node_modules/graceful-fs/fs.js:1:64)
      at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:3:27)
```