Use testRegex instead of testMatch
Now, the tests actually run, and they fail in exactly the same way that
the tests failed running under "ava", probably because my version of
Node is several years too new for this project:

    ReferenceError: internalBinding is not defined